services:
  jenkins-controller:
    build:
      context: docker/images/jenkins-controller
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/volumes/jenkins-home:/var/jenkins_home:cached
    ports:          # HOST:CONTAINER
      - 8080:8080   # Jenkins UI
      - 8000:8000   # Jenkins Master Debugging Port
    environment:
      - GITHUB_APP=${GITHUB_APP_KEY}
      - TRY_UPGRADE_IF_NO_MARKER=true
      - JAVA_OPTS= -Dstapler.jelly.noCache=true  -Dhudson.remoting.ClassFilter=com.google.common.collect.ImmutableListMultimap -DexecutableWar.jetty.disableCustomSessionIdCookieName=true -DexecutableWar.jetty.sessionIdCookieName=warnings-ng-devenv -agentlib:jdwp=transport=dt_socket,address=*:8000,suspend=n,server=y
    user: ${CURRENT_UID}
    restart: unless-stopped
  java-agent:
    build: ./docker/images/java-agent
    ports:
      - 8001:8001   # Jenkins Agent Debugging Port
    depends_on:
      - jenkins-controller
    restart: unless-stopped
  java-11-agent:
    build: ./docker/images/java-11-agent
    ports:
      - 8002:8002   # Jenkins Agent Debugging Port
    depends_on:
      - jenkins-controller
    restart: unless-stopped
